- .jshintrc
- .npmignore
- .travis.yml
- README.md
- package.json
* I removed `globals` from [.jshintrc](https://github.com/wearefractal/vinyl-fs/blob/master/.jshintrc). It's unnecessary because `mocha` option is enabled.
* I removed .npmignore file. It's unnecessary because package.json has `main` field.
* I added `sudo: false` to [.travis.yml](https://github.com/wearefractal/vinyl-fs/blob/master/.travis.yml) to use [container-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) on Travis CI.
* I updated image format of the badges in readme from PNG to SVG. SVG badges look beautiful on retina display.
* I introduced [istanbul-coveralls](https://github.com/shinnn/istanbul-coveralls).
> Update dotfiles and readme

- README.md
- lib/src/index.js
- package.json
- test/src.js
> Add `passthrough` option, fixes #25, fixes gulpjs/gulp#840

- README.md
- lib/dest/writeContents/index.js
- lib/dest/writeContents/writeBuffer.js
- lib/dest/writeContents/writeStream.js
- lib/prepareWrite.js
- test/dest.js
This is in reference to: https://github.com/wearefractal/vinyl-fs/issues/30
It seemed like the overwrite option was stubbed out, but the `wx` flag was never utilized in the fs operations. This commit wires it up, handles the error catch scenario and adds some tests. Let me know what you think!
> Implemented `overwrite` option in `dest()`

- lib/dest/writeContents/index.js
- test/dest.js
Related to #61, I found that the actual issue is currentMode gets its flags stripped by the bitwise comparison, but not the destination mode. This adds bitwise comparison to the dest mode to fix detection of different modes.
> Fix mode comparison

- package.json
this relies on the recent breaking changes to glob-watcher being published to npm as 2.0
@contra this will cause vinyl-fs to require a 2.0 bump also.
> switch to glob-watcher 2.0

- test/dest.js
It has been shown in #62 this bit can be platform specific and is unreliable, testing fs.chmod is not called will be enough.
> Remove realMode equality test on special bit test

- lib/src/index.js
- package.json
- test/src.js
If a nested array: `[ ['./fixtures/*.coffee'] ]` is passed, the current `isValidGlob` method will return `true` and `glob-stream` will end up throwing an 'Invalid glob at index 0` error.
Using `is-valid-glob` handles this case and causes `src` to throw an `Invalid glob argument: ` error instead.
Added test to validate.
> using is-valid-glob module to handle nested arrays properly

- .travis.yml
- README.md
- lib/prepareWrite.js
Make readme more consistent
test on iojs and 0.12	
Expose `options.base` for `dest`
Because the stream returned from `dest` is also readable, it is kinda link a `src` to the next `dest` so the `base` should be configurable just like `src`.
> Improvements

- package.json
See https://docs.npmjs.com/files/package.json#dependencies and https://github.com/nodejs/io.js/issues/2223.
> use valid semver range for `engine`

- README.md
- lib/dest/writeContents/index.js
- lib/dest/writeContents/writeSymbolicLink.js
- lib/src/getContents/index.js
- lib/src/getContents/readSymbolicLink.js
- lib/src/index.js
- lib/src/resolveSymlinks.js
- test/dest.js
- test/src.js
The current behavior is always to resolve symbolic links to actual
files.
This change introduces a `keepsymlinks` option to `src()`. When the
option is set, the destination of each encountered symbolic link is stored
in `file.symlink`. When `dest()` is invoked, the `symlink` value is used
to reconstruct identical symlinks.
It is important to note that the symbolic link path remains completely
unmodified, so care should be taken when sourcing symlinks with absolute
paths.
If found to be sufficient, I'm fairly certain this patch resolves issue #50
> Add symlink passthrough with `followSymlinks`

- README.md
- lib/src/getContents/bufferFile.js
- lib/src/getContents/streamFile.js
- lib/src/index.js
- test/src.js
@contra PRed for review
Should be a minor release (2.1.0)
> add option to strip BOM, default to true - closes #83

- .travis.yml
updated as part of #92, removing iojs and adding in node.js 4.0, 4.1
> updated to test on nodejs 4

- README.md
Some of the links were broken in the README, I have changed all of them except coveralls.  It doesn't look like there's gulpjs/vinyl-fs coveralls configured.
> Fix links, spacing in README

- lib/utimes.js
- test/dest.js
> Check if `atime` Date object is invalid and set a new one explicitly

- lib/dest/writeContents/writeBuffer.js
- lib/dest/writeContents/writeStream.js
- lib/futimes.js
- test/dest.js
Figured it wasn't too much trouble to propose something concrete re: [this](https://github.com/gulpjs/vinyl-fs/issues/124).
> Use `fs.futimes` to retain sub-second precision in `atime` and `mtime`

- lib/dest/index.js
- test/dest.js
This PR fixes a TypeError that's thrown when a boolean `sourcemaps` option is passed to `dest` e.g.:
```javascript
fs.dest(dir, { sourcemaps: true })
```
```javascript
'use strict'
let coffee = require('gulp-coffee')
let fs     = require('vinyl-fs')
let rename = require('gulp-rename')
fs.src('./input.coffee', { sourcemaps: true })
.pipe(coffee({ sourceMap: true }))
.pipe(rename('output.js'))
.pipe(fs.dest('.', { sourcemaps: true }))
```
```coffeescript
console.log 'Hello, world!'
```
$ node ./test.js
```
test/node_modules/gulp-sourcemaps/index.js:144
options.includeContent = true;
^
TypeError: Cannot assign to read only property 'includeContent' of true
at Object.write (test/node_modules/gulp-sourcemaps/index.js:144:28)
at Object.dest (test/node_modules/vinyl-fs/lib/dest/index.js:28:30) …
```
> fix TypeError when the dest sourcemaps option is a boolean

- lib/dest/index.js
- lib/sink.js
- package.json
- test/dest.js
@contra  I think I solved #120 with this.  Can you take a look? I made the test and it was failing and then I made it pass.  @davidchase could you also take a look at this?
Closes #120
> read from the stream once we finish processing a file, this avoids highWaterMark being hit - add test

- README.md
After discussing it with @phated in #129, it seems to me that the previous description of the default `base` value is incorrect in the docs. I was originally unsure where the source of truth was (docs or code) but it seems that the code is correct.
> #129 - Update documentation to more clearly explain what happens for default base option values.

- lib/src/getContents/streamFile.js
- package.json
- test/dest.js
It appears as though streamFile was creating duplicate ReadStreams,
which somehow was causing the process to never free WriteStreams. Also
I've changed the removeListeners calls to unlisten to `complete` rather
than `cb`, since they're never told to listen to `cb` in the first
place.
I suspect this is related to #56 ?
> Fix file descriptor exhaustion when streaming many files

- lib/src/index.js
- test/src.js
As promised in [#153](https://github.com/gulpjs/vinyl-fs/issues/153)
> Don't pass `read` option from `src` to `through2`

- lib/fileOperations.js
- test/destModes.js
- test/fileOperations.js
Ref #156 
Let me know if you need me to get rid of the merge commit, I can open a new branch and apply the changes there if need be.
Thanks everyone for the help!!
> Support setting setuid/setgid/sticky in updateMetadata and adapt tests

- test/dest-modes.js
- test/dest.js
- test/file-operations.js
- test/symlink.js
I think this fixes [#166](https://github.com/gulpjs/vinyl-fs/issues/166), and also has the tests use octal strings for expected results (easier to troubleshoot mode issues).
> Make tests aware of umask, and use octal strings for expected results

- README.md
Available in gulp-stream, but not documented here.
> Add documentation for `dot` option

- README.md
- lib/default-value.js
- lib/dest/index.js
- lib/prepare-write.js
- lib/src/index.js
- package.json
- test/default-value.js
- test/src.js
It is not entirely clear from the issue if it is only about `src` or if `dest` is also in scope. Anyway, here it is for `src`. I can replicate the behavior for `dest` very simply.
A few notes:
- I think mixing vinyl-fs options and through2 options in the option object can be error-prone (https://github.com/gulpjs/vinyl-fs/issues/153) and can complexify the implementation (see how I need to avoid calling through2 options that are functions?). May I suggest moving through2 options to a through2 property in vinyl-fs options? I believe that would be simpler and clearer, both for the caller and the callee. It would be a breaking change.
- I did not use `value-or-function` because I did not see the benefit of checking the types of the options. Also I saw defaulting to `null` as a bit dangerous …
> Support functions for all src options (fix #139)

- lib/dest/index.js
- lib/dest/write-contents/index.js
- lib/dest/write-contents/write-buffer.js
- lib/dest/write-contents/write-dir.js
- lib/dest/write-contents/write-stream.js
- lib/dest/write-contents/write-symbolic-link.js
- lib/prepare-write.js
- lib/symlink/index.js
As discussed [here](https://github.com/gulpjs/vinyl-fs/issues/158).
> Remove superfluous argument from write-xxx modules

- lib/dest/write-contents/write-buffer.js
- lib/dest/write-contents/write-dir.js
- lib/file-operations.js
- test/file-operations.js
As discussed [here](https://github.com/gulpjs/vinyl-fs/issues/158).
> No need for updateMetadata to pass fd to callback

- test/dest-times.js
In response to this [failing Travis build](https://travis-ci.org/gulpjs/vinyl-fs/jobs/135799053) -- it seems to me this happens only very rarely, but this patch should make it rarer still.
> Increase offset in futimes test stamps

- lib/dest/writeContents/writeDir.js
- lib/fileOperations.js
- lib/prepareWrite.js
- package.json
- test/dest.js
- test/fileOperations.js
Custom mkdir implementation that include the ability to update the
permissions mode on a directory that already exists.
This is an initial cut at this feature that works with passing unit tests on OS X.  Haven't been able to verify Windows and Linux compatibility yet.
There are also probably coding convention and style preferences to fix.
> Custom mkdirp (Issue #165)

- lib/constants.js
- lib/file-operations.js
- test/dest-modes.js
As discussed [here](https://github.com/gulpjs/vinyl-fs/issues/158).
> Introduce module for constants

- lib/file-operations.js
- test/dest-owner.js
- test/file-operations.js
This PR adds support for changing the uid/gid of a file/directory.
Changing the uid/gid of a file is only possible as the root user and will fail silently if this run as a non root user.
What do you think we should do in this case?
> Added support for changing uid/gid (fix #157)

- test/not-owned.js
Pedantic, I know, but it looked off :-)
> Add space to not-owned notices

- README.md
The option to include dot files is `options.dot` rather than `options.dots`. See the [documentation for node-glob](https://github.com/isaacs/node-glob/blob/68f2509d237babec64cf03adf72531127fd80339/README.md#options).
> Correct `dot` option in README.md

- README.md
- lib/dest/write-contents/write-stream.js
- lib/symlink/index.js
- test/symlink.js
This is just a reference PR for #211 because I'm not sure if the original author has time to finish this up.
TODO:
> Fix #210 Windows symbolic links requiring admin

- .travis.yml
- test/not-owned.js
I don't remember why I closed a similar [PR](https://github.com/gulpjs/vinyl-fs/pull/198) earlier, but I ran into this again today (on Linux, changing owner to root was not enough to make the not-owned tests pass, had to change mode as well).
I'm not sure why it works on Travis, actually. Could be a umask difference, or something like that.
Shouldn't conflict with the prepare work, I expect.
> Check mode of not-owned.txt, avoid repeated notices

- lib/dest/options.js
- lib/dest/write-contents/index.js
- lib/dest/write-contents/write-symbolic-link.js
- lib/file-operations.js
- lib/symlink/index.js
- lib/symlink/link-file.js
- test/dest-symlinks.js
- test/dest.js
@erikkemperman does this address your thoughts from your last comment in #239?  `vfs.symlink` doesn't add the `.symlink` property yet (probably a separate thing to address).
A side thought: the `relative` option should probably renamed to `relativeSymlinks` for the `vfs.dest` method.
> Dest symlinks

- lib/dest/options.js
- lib/dest/write-contents/write-symbolic-link.js
- lib/symlink/link-file.js
- lib/symlink/options.js
- test/dest-symlinks.js
- test/symlink.js
With this change, I think it was proper to change the `relative` logic to check against the `symType` and only reject the option if it is trying to generate a `junction`.
I also added more tests for the scenario I am solving with these changes.
/cc @erikkemperman
> Simplify `useJunctions` default

- README.md
- test/dest-times.js
- test/file-operations.js
- Use `new Date()` instead of `fs.statSync(__filename).mtime` as `file.stat.mtime`
- Fix all cases mentioned in https://github.com/gulpjs/vinyl-fs/issues/208
- Make a note about precision lost in 32bit Node.js
> Fix utime-related test cases

- lib/src/read-contents/index.js
Separate PR, as per @phated's comment on https://github.com/gulpjs/vinyl-fs/pull/257.
> Read-contents/index, invoke cb with error or result, not both

- README.md
As per https://github.com/gulpjs/vinyl-fs/pull/258#issuecomment-314924964
> Docs: reword 32-bit timestamp precision issue

- .editorconfig
- .gitattributes
This will enforce *nix line endings even on Windows checkouts, and will inform editorconfig-aware editors of same. If you like this change, we'll probably want it across the various gulpjs repos. Let me know and I'll make a bunch of PRs for it!
> Build: enforce consistent line endings

- lib/dest/prepare.js
- lib/symlink/prepare.js
- test/dest.js
- test/symlink.js
- test/utils/break-prototype.js
@erikkemperman @asgoth @stevelacy @doowb What do y'all think of this as the solution to #288 and gulpjs/gulp/issues/2065
> Fix: Marshall old Vinyl objects to new Version in dest()

- test/integration.js
testConstants does not have a `content` property, it has a `contents`
property.  Reference the correct name to make tests pass.
> Reference correct property name in integration testing

- lib/src/prepare.js
- test/src.js
Closes #226
This adds `ctime` as a property to be considered when `since` filtering. The `ctime` might be changed by some file metadata change and that should be considered a file change.
> feat!: Consider the greater of ctime & mtime when comparing since option

- lib/file-operations.js
- test/file-operations.js
Closes #302
We attempt to reflect the vinyl stats to the filesystem using `futimes`, but if a system doesn't allow that due to ENOSYS, we don't want to error; however, the vinyl file stats need to match the filesystem stats, so we now sync them with the filesystem stats. This is fixing the issue, but is also a breaking change in how those stats are reflected.
> fix!: Avoid error and reflect filesystem stat if futimes not implemented

- lib/src/index.js
- test/src.js
I broke `src()` with arrays of globs with my changes in #333
This converts all glob arguments to arrays and then normalize the entire array of globs.
> fix: Correct regression with src using arrays of globs

- test/src.js
Closes #306 
We switched our implementation of `to-absolute-glob` to a fork that supports negative relative globs. This is just a regression test showing it works.
> fix: Add regression test for negative relative globs

- lib/symlink/prepare.js
- test/dest.js
- test/src.js
- test/symlink.js
Closes #245
Closes #303
This brings the `symlink()` stream closer to how `dest()` writes symlink files. The `dest()` function always expects the `file.symlink` property was set; however, `symlink()` exists to create symlinks without setting that property. This causes us to encounter a problem in `symlink()`, such that if you rename a file, it will create a dangling link.
While we could direct people to use `dest()` for this behavior, it seems fine to prefer the `file.symlink` property if it is set.
> feat!: Prefer symlink property set on Vinyl object over its path

- .github/workflows/dev.yml
- test/codecs.js
- test/dest-modes.js
- test/dest-owner.js
- test/dest-symlinks.js
- test/dest-times.js
- test/dest.js
- test/file-operations.js
- test/integration.js
- test/not-owned.js
- test/src-symlinks.js
- test/src.js
- test/symlink.js
- test/utils/cleanup.js
CI was horribly broken when trying to run #358 tests.
> chore: Fix CI

- package.json
This updates glob-stream to require the latest patch which ensures globs aren't traversed until the read stream is opened. I am hoping this will fix the issue people are encountering where the stream doesn't seem to process their files.
> fix: Avoid globbing before read stream is opened
