gulpjs/vinyl-fs

package.json
Fix https://github.com/wearefractal/vinyl-fs/pull/52#issuecomment-69107876
=> Remove unnecessary `coveralls` from devDependencies

test/dest.js, test/symlink.js
=> add missing test for f7516ebac102104ad0f39437f7739bf5aedec165

README.md
Follow up with 3e2a5ef63c98b9ef44b3d05cdc6c03bdb9c2392b
=> symlink opt.base should be the same as dest

README.md
=> fix wrong event name in README.md

package.json
=> Updated merge-stream version to 1.0.0

README.md, lib/prepareWrite.js, test/dest.js
=> allow a function to be used as value for the overwrite option - closes #68

test/dest.js, test/spy.js, test/src.js, test/symlink.js
Please consider upgrading tests.
=> Update tests to 'strict mode'

lib/dest/writeContents/utils.js, lib/dest/writeContents/writeBuffer.js, lib/dest/writeContents/writeStream.js, lib/utimes.js, test/dest.js
=> Set utimes of files if they are provided

lib/utimes.js, test/dest.js
=> [Fix] Ignore atime and mtime if they are invalid

lib/dest/writeContents/writeStream.js
=> Change writeStream callbacks from cb to complete

.travis.yml, test/dest.js, test/symlink.js
As per @OnkelTem's suggestion in #103 
@contra @OnkelTem please review.
=> Make tests ignore gid

lib/dest/writeContents/writeStream.js, test/dest.js
I'm fairly certain this addresses the issue in #137. Includes a unit test.
=> Rework writeStream to prevent issue with futimes

README.md
Fixes #135 
@contra please review thoroughly
=> drastically improve docs

lib/sink.js, test/dest.js
Closes #142 
@chrisdickinson singular diff, what do you think?
=> Allow things to listen for data or readable events and avoid sinking in those cases

package.json
Cross-ref: https://github.com/gulpjs/vinyl/pull/77 (more details there)
=> chore: add NPM script for changelog

lib/dest/write-contents/write-stream.js
As discussed [here](https://github.com/gulpjs/vinyl-fs/issues/158).
=> Don't rely on undocumented Stream.fd property

lib/dest/write-contents/index.js, lib/dest/write-contents/write-buffer.js, lib/dest/write-contents/write-dir.js, lib/dest/write-contents/write-stream.js, lib/dest/write-contents/write-symbolic-link.js, lib/src/get-contents/index.js, lib/src/get-contents/read-buffer.js, lib/src/get-contents/read-dir.js, lib/src/get-contents/read-stream.js, lib/src/get-contents/read-symbolic-link.js
@phated This was in my aesthetix branch I linked to earlier, but couldn't make a PR for it at the time because of conflicts. It is completely cosmetic, but you said you liked it, so here goes.
=> Consistent callback names

README.md, lib/symlink/index.js, test/symlink.js
Adds support for creating symlinks which point to a file relatively
=> Add relative symlink support

lib/src/resolve-symlinks.js
Getting back to this stuff after a while, and as it now feels like things are nearing a milestone, I wanted to get a few things that I've played around with earlier off my chest.
Tried to keep commits tidy but figured I'd make a single PR for them, hope that's all right. If there's things in here you don't like, and cherry-picking turns out to be finicky, please do let me know and I'll amend accordingly.
=> No need for realpath calls, just expose the right stat

README.md
=> Cleanup options documentation

lib/symlink/link-file.js
Fixes https://github.com/gulpjs/vinyl-fs/issues/298
=> Fix sloppy/paste

test/integration.js
Closes #310
See my comment for details about child process streams being poorly behaving.
=> chore: Add integration test for re-assigning a stream to contents

lib/src/read-contents/read-stream.js, package.json
Closes #336
This replaces lazystream by just using a `stream-composer` where we swap out the pipeline on `open`
=> feat: Replace lazystream with streamx Composer

CHANGELOG.md
cc @aikebah @elitastic
Next time, feel free to send the update 👍 
Ref #347
=> chore: Add breaking encoding option to changelog
